name: hydrotools.metrics

on:
  push:
    paths:
    - 'python/metrics/**'
  pull_request:
    paths:
    - 'python/metrics/**'
  workflow_dispatch:

jobs:
  unittests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install ./python/metrics[develop]
    - name: Echo dependency versions
      run: |
        python3 -m pip freeze
    - name: Run unittests 
      run: |
        python3 -m pytest -s -m "not slow" ./python/metrics/
